### ISSUE TITLE
Can't use route's params in head. 

### ISSUE THREAD

**Issue by SidKwok** [ktquez/vue-head#15]
If I use param with route in head, it works, but it won't change if I change to another param .
```
head: {
            title() {
                return {
                    inner: `${this.$route.params.type}file`
                }
            }
        }
```

**Comment by ktquez** [comment]
I did not understand well @SidKwok

**Comment by SidKwok** [comment]
I mean `vue-head` is not reactive.

This is my router:
```
...
'/apps/:type': {
    component:  Apps,
}
...
```

Now I have two urls: `/apps/crash` and `/apps/block`.

And I set in the component `Apps`:

```
head: {
            title() {
                return {
                    inner: `${this.$route.params.type}file`
                }
            }
        }
```

`this.$route.params.type` is reactive, but the `head` is not.

How can I make it reactive? Or it just can't?

Sorry for my poor English.......

**Comment by ktquez** [comment]
That same @SidKwok to the current version of vue-head it only builds the head tags when the component is mounted.

Take a look at this increasing discussion [Issue 13](https://github.com/ktquez/vue-head/issues/13#issuecomment-244543821)

Thank you for using the plugin and the feedback.

**Comment by SidKwok** [comment]
Thanks! Good plugin! But when will the feature come out? Can't wait! LOL!
