### ISSUE TITLE
Title reverts to default when changing route

### ISSUE THREAD

**Issue by bryceadams** [ktquez/vue-head#16]
Hi! Sorry if this isn't really a bug, but I thought I'd see if you knew of a similar issue. This issue is when using [Spark](http://spark.laravel.com).

The default/main title is set in the head's HTML, like:

```
<title>My Site</title>
```

And the title defined through vue-head in a component. When the page is first loaded, the title displays correctly, combining 'My Site' with the title in the component.

However, when going to a different page (through `vue-router`), it flashes the proper combined title for a second and then reverts back to just 'My Site'.

If I remove the default/main title from the head's HTML, it works as expected.

Any ideas? :) Thanks!

**Comment by ktquez** [comment]
Hello man, lost on me that question, thanks for the feedback.
I will now correcting it, you can follow this [issue 17](https://github.com/ktquez/vue-head/issues/17#issue-175639231).
The next version is already available what you need.
Thank you.

**Comment by bryceadams** [comment]
For others with a similar issue, what I ended up doing was removing the title in the HTML and then adding a mixin that set the following:

```
    head: {
        title: function() {
            return {
                inner: this.title,
                complement: 'App Name',
            }
        }
    }
```

Each component then adds this mixin and sets `title` in the `data` component.

**Comment by ktquez** [comment]
@bryceadams 
Excellent solution, much better.
