### ISSUE TITLE
Next feature

### ISSUE THREAD

**Issue by ktquez** [ktquez/vue-head#17]
Thank you all for the feedback.
Is already in production some improvements and new features.

- [X] Meta tags with support to update data

**Comment by ktquez** [comment]
v2.0.3

**Comment by JosephSmith127** [comment]
@ktquez nice work but I get an error when I run the this.$emit function of

`vue-head.js?e7cb:108 Uncaught (in promise) TypeError: Cannot read property 'isEqualNode' of undefined(…)`

**Comment by ktquez** [comment]
@JosephSmith127 
How is your code?

**Comment by JosephSmith127** [comment]
Yeah I am using the latest version. So I have a shared variable shared through components. Within that I have set the page params array with the information. Like so,

```
params: {
    title: 'website name',
    description: 'website description',
    image: false,
    app: 'app name',
},
```

Which then on the main route app I have the set variables reading from this shared array, like so,

```
head: {
		title: function () {
      		return {
				inner: this.shared.params.title,
				separator: '',
    			complement: ''
			}
		},
		meta:  function () {
			return [
				{ name: 'application-name', content: this.shared.params.app },
				{ name: 'description', content: this.shared.params.description },
				{ name: 'twitter:title', content: this.shared.params.title },
				{ n: 'twitter:description', c: this.shared.params.description},
				{ p: 'og:image', c: this.shared.params.image },
		 	]
   		},
	},
```

and then when the other components are loaded I update the shared information, and then `this.$emit('updateHead');` in which I receive this error.

<img width="1440" alt="screen shot 2016-09-09 at 00 41 36" src="https://cloud.githubusercontent.com/assets/4484836/18370593/38afeca6-7626-11e6-9891-c32700bb6bc2.png">

**Comment by ktquez** [comment]
@JosephSmith127 
Your code is just ok, I tried to simulate this error happens to you, but I could not.

However I added a few more lines, that may be correct.
Try the version `v2.0.6`

Thank you

**Comment by JosephSmith127** [comment]
@ktquez When ever I try to update it always pulls v2.0.5 and when changing it in package.json manually it says :

```
npm ERR! No compatible version found: vue-head@2.0.6
npm ERR! Valid install targets:
npm ERR! 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.0.1
```

**Comment by JosephSmith127** [comment]
I think you need to update npmjs for the next version. But either way I manually tired the updated code by just copying from github, the console error has gone, but page names are not changing.

**Comment by JosephSmith127** [comment]
Yeah so @ktquez the console errors go, but the issue I am having still remains. The title of the site is just.

Website name | Website name

on every page... even though that even by default I just set it to "Website name", and on every page its updated...  any ideas?

**Comment by vahdet** [comment]
> Yeah so @ktquez the console errors go, but the issue I am having still remains. The title of the site is just.
> 
> Website name | Website name
> 
> on every page... even though that even by default I just set it to "Website name", and on every page its updated... any ideas?

You may need to emit `updateHead` event as mentioned here: https://github.com/ktquez/vue-head/issues/13#issuecomment-258112042
