### ISSUE TITLE
Open Graph does not work

### ISSUE THREAD

**Issue by tvld** [ktquez/vue-head#27]
Open Graph recognizes:
```html
<meta property="og:url" content="https://www.mysite.com">
```
But not:
```js
head: {
      meta: [
        { property: 'og:url', content: 'https:/www.mysite.com' }
      ],
```
It seems that OG only checks the index.html and does not wait for any js? In that case vue-head is useless and the README.md wrongly specifies it can be used?

Using ``opengraphcheck.com`` to test.

**Comment by ktquez** [comment]
While social networks do not adapt, they will not identify.
However the plugin is just an anticipation for future SPA support and tags head mounted by javascript.
At the moment only the search engines can properly render such sites.

Render on the server side is a reality and can work for this purpose.

**Comment by tvld** [comment]
I figured that. Maybe you can include that answer in the readme? I will close the issue ;)

**Comment by ktquez** [comment]
Yes I will, thank you @tvld
