### ISSUE TITLE
question: get head from the server

### ISSUE THREAD

**Issue by paulocheque** [ktquez/vue-head#3]
First of all, the library is great! Very simple to use. Now the question:

For example, I would like to have a Component that will have a custom `fb:app_id`. But to get this id, I will have to make a request to the server.

But my tests failed, even using the functions to return the components. I tried to load the server information in the `created` phase of the component. https://vuejs.org/guide/instance.html#Lifecycle-Diagram

Do you think this is possible? What do you recommend for this scenario? Maybe using transition hooks (http://router.vuejs.org/en/pipeline/hooks.html)?

Well, this data is important for SEO, so I don't think any JS will be useful, but.. dunno

Thanks in advance!

**Comment by ktquez** [comment]
Olá @paulocheque, tudo ok?
Não sei se entendi, mas se estiver utilizando o vue-router, é melhor utilizá-lo para isso

```
meta () {
  return {
    property: {
        'fb:app_id': 123456789
 
  }
}
```

**Comment by paulocheque** [comment]
Opa, jóia!

Ok, thanks. Well, this is what I imagine. We could use `data` instead of `activate`, but either way it is javascript, so this can be problematic for most robots. But for some properties this could be very useful. Thanks again!

**Comment by ktquez** [comment]
This would talk about not facebook detection in dynamic data.
now is not cool, but they will adapt, I'll cheer for it.

Yeah, `data` It is most recommended

**Comment by stephanedemotte** [comment]
Hi !

First, thanks for this cool plugin !

We want to use it with Vue 2.0

I have fork your repo here [https://github.com/kffein/vue-head](url)
I have simply change `ready` for `mounted`

But it seem to be not reactive in my component...

```
  data () {
    return {
      title: '' 
    }
  },
  mounted() {
    setTimeout(() => this.title = 'titi', 1000)
  },
  head: {
    title() {
      return {
        inner: this.title,
      }
    },
  }
```

the title still empty after 1 seconde...

Any idea ?

Thanks !

**Comment by ktquez** [comment]
@stephanedemotte 
Thanks for using!

I have not ventured in 2.0, but have you tried to `updated` hook?

> From what I read, the `mounted` does not guarantee much if the DOM is ready.

If you can make it work, send a pull request as v2.0.0-beta.

I will begin testing the 2.0 and test the vue-head plug
Thanks for the feedback.
