### ISSUE TITLE
Async update not working

### ISSUE THREAD

**Issue by tobeorla** [ktquez/vue-head#30]
With Vue 2.0 async update stopped working. No errors are begin displayed.

I've checked your example but i think it can't run since uses "ready" method that got deprecated in Vue 2.0 :s
https://github.com/ktquez/vue-head/blob/master/example/index.html#L98

**Comment by ktquez** [comment]
I'm sorry @tobeorla, I forgot to change the method, however using the `mounted` in the example, it works correctly, making the update.
