### ISSUE TITLE
Changing the default title separator

### ISSUE THREAD

**Issue by jgerbes** [ktquez/vue-head#36]
It may already be possible to change the default title separator ("|"), but the documentation doesn't cover how to do so.

Please confirm whether or not this is possible, and how it can be done.

**Comment by ktquez** [comment]
Hi @jgerbes 
Thanks for using the vue-head

É possível sim, dá uma olhada nesse link:
https://github.com/ktquez/vue-head#custom-title

**Comment by jgerbes** [comment]
Hi @ktquez,

That allows a custom separator for each component, but doesn't change the default separator

**Comment by ktquez** [comment]
@jgerbes 
Sorry, I will soon put this in the documentation.
Actually has a way to change the default tab through the options when installing the vue-head.
```javascript
const VueHead = require('vue-head')

Vue.use(VueHead, {
  separator: '-'
}
```
