### ISSUE TITLE
[Help] ES6 syntax

### ISSUE THREAD

**Issue by gazpachu** [ktquez/vue-head#38]
I'm trying to figure out how to compose titles using variables defined in `data`, but I don't seem to find the proper way of making `this` work. I always get this error: `TypeError: Cannot read property 'editing' of undefined`.

```
head: {
    title: () => {
      return {
        inner: this.editing ? 'Edit Participant' : 'Create Participant',
      };
    },
  },
  data() {
    return {
      editing: false,
    }
  },
```

I've also tried like this, but no luck:

```
data: () => {
  return {
    editing: false
  }
}
```

**Comment by ktquez** [comment]
Hello @gazpachu 
Try this way to see if it works.

```
head: {
  title () {
    return {
      inner: this.editing ? 'Edit Participant' : 'Create Participant',
    }
  }
},

data () {
  return {
    editing: false
  }
}
```

**Comment by gazpachu** [comment]
Thanks @ktquez, something like that seemed to work.
