### ISSUE TITLE
Provide proper documentation

### ISSUE THREAD

**Issue by airtonix** [ktquez/vue-head#4]
Great idea for a library, however by following your recomendation to read [https://github.com/joshbuchea/HEAD](https://github.com/joshbuchea/HEAD)  it's not really obvious as to how I should be structuring  the object inside `head`.

For instance, your example of setting the document title:

```js
...
	head: {
		title: {
			separator: ' - ',
			inner: 'Foo',
			complement: 'Bar'
		}
	},
...
```

I am unable to find the words `inner` or `compliment` on [https://github.com/joshbuchea/HEAD](https://github.com/joshbuchea/HEAD).

**Comment by ktquez** [comment]
Yes, we do not find there the HEAD this structure, but had defined so because of the need for a more structured basis, similar to wordpress SEO.
