### ISSUE TITLE
Won't wait the beforeRouteEnter

### ISSUE THREAD

**Issue by gfviegas** [ktquez/vue-head#40]
I'm trying to apply dynamic data on my tags but i'm struggling since all data is going empty because the head won't wait the HTTP fetch the data:

```
export default {
    [.....]
    head: {
      title () {
        console.info(JSON.stringify(this.data))
        return this.data.title
      }
    },
    beforeRouteEnter (to, from, next) {
      myService.fetch().then((response) => {
        next((vm) => {
          console.log('BeforeRouteEnter complete!')
          vm.data = response.body
        })
      })
    }
}
```

And my console output:

```
> {title: ''}
> BeforeRouteEnter complete!
```

**Comment by ktquez** [comment]
Hello @gfviegas 
You can issue the event [updateHead](https://github.com/ktquez/vue-head#update-elements-with-asynchronous-data-or-after-page-loaded) so that the metatags are rebuilt.
`` this.$emit('updateHead') ``

**Comment by gfviegas** [comment]
Sure thing, but that will fire the ok head event twice, wont it?

**Comment by ktquez** [comment]
Sorted out? @gfviegas
