### ISSUE TITLE
Trim title before final output

### ISSUE THREAD

**Issue by andreasvirkus** [ktquez/vue-head#41]
Greetings,

Wondering if you'd like to implement a simple whitespace trim before the title's final output? Currently it leaves whitespaces if for example my separator and complement are single whitespace strings (can't set actual zero-length strings).

      var title = obj.inner + ' ' + (obj.separator || opt.separator) + ' ' +  (obj.complement || opt.complement);
      window.document.title = title.trim();

**Comment by ktquez** [comment]
@andreasvirkus 
Can you show me the result? For me to try to understand better.
If it is to improve or solve a problem, send a pull request for me to merge.

**Comment by ktquez** [comment]
Send a pull request, thanks

**Comment by rivieiraa** [comment]
He meant that you should make separator and complement params optional.
`Vue.use(VueHead, {
    inner: 'Bridge SA',
    separator: '',
    complement: ''
});
.....

...
head: {
        title: {
            inner: 'Our rewards'
        },
        // Meta tags
        meta: [
            {name: 'description', content: 'A description of the Awards page'}
        ],
    }
....`

gives title like on screenshot here http://take.ms/yW5pS

**Comment by andreasvirkus** [comment]
Exactly. I can make a PR but it'll be mid-April when I'm back from travelling.
