### ISSUE TITLE
can you tell me the head when work?

### ISSUE THREAD

**Issue by liufeisprit** [ktquez/vue-head#47]
the mounted work?

**Comment by liufeisprit** [comment]
@ktquez

**Comment by ktquez** [comment]
@liufeisprit 
I don't get it. Please, explain your question.

**Comment by liufeisprit** [comment]
I use the head to import external js which is very long. And it encapsulates some ajax methods which will have to wait until the external js loaded. So I want to know when the head is running. I want to let it run faster and  finish loading external js.

**Comment by liufeisprit** [comment]
@ktquez

**Comment by ktquez** [comment]
If I understood correctly, you can use ``async``

**Comment by liufeisprit** [comment]
![image](https://user-images.githubusercontent.com/25600325/26957500-09e0fa56-4cf8-11e7-943a-940c4a46c8a2.png)
Of course I use it but it's no void

**Comment by ktquez** [comment]
Yes, working in hook mounted. 
[See here](https://github.com/ktquez/vue-head/blob/master/vue-head.js#L237).

**Comment by liufeisprit** [comment]
Can you tell me why I use vue - head to load multiple js? Is there a caching problem for webpack
![image](https://user-images.githubusercontent.com/25600325/27513719-f096e43a-59a3-11e7-844d-6d0f248f3563.png) 
Each route loads multiple external js
@ktquez

**Comment by liufeisprit** [comment]
thank you very much
