### ISSUE TITLE
Update head append Title and not replace

### ISSUE THREAD

**Issue by mazipan** [ktquez/vue-head#49]
Why when emit updateHead with the title inner not replace but append with the default value

**Comment by mazipan** [comment]
I use setup like
```
head: {
    title: function () {
      return {
        inner: this.metaTag.title
      }
    },
    meta: function () {
      return this.metaTag.meta
    }
  },
watch: {
    metaTag: function (newValue, oldValue) {
      if (newValue !== oldValue) {
        this.$emit('updateHead')
        // I need to add this force update title, is it Bug ?
        document.title = this.metaTag.title
      }
    }
  },
```

**Comment by ktquez** [comment]
Should work.
I will do a test and I will bring a solution, but nothing should be with the `vue-head`

**Comment by mazipan** [comment]
Now, I use that solution for production 😅.
But I think it's not good.
Because in my expectation was will replace the title without set manually

**Comment by ktquez** [comment]
If you need it, just open it again, okay?
Thanks for using the plugin
