### ISSUE TITLE
tag with id is not added to document

### ISSUE THREAD

**Issue by sutra** [ktquez/vue-head#52]
https://github.com/ktquez/vue-head/blob/93b4d2e6b1dd8eb964befe0dfd806a9fb4edf4f0/vue-head.js#L149-L152

These lines make the new(not exists in dom already) tags with ID do not add to document.
I am not sure if this is by design, but I think this behavior does not make sense.

**Comment by mattcurtis** [comment]
I would just add to this that the example for .vue files on your README still includes the id on its meta description tag:

```
    meta: [
      { name: 'description', content: 'My description', id: 'desc' }
    ]
```

It would be useful to update that if you decide to keep this behaviour, I wouldn't have figured it out why it wasn't working if @sutra hadn't raised the issue.

(Thanks @ktquez and contributors for vue-head btw, very useful project)

**Comment by ktquez** [comment]
@mattcurtis 
Thanks for using.

@sutra 
I'm rewriting this plugin to add SSR support and fix some problems reported here.
We'll have something this week.

**Comment by kopepasah** [comment]
@ktquez is there any update on when this might support IDs in elements?

**Comment by sebj54** [comment]
I just encountered this issue too. 
Do you need someone to do a PR? Just asking to see if I'm not doing it for nothing :)

**Comment by ktquez** [comment]
@sebj54 
If you want to do a PR, thank you.
I'm a little busy and out of time.

I would be very grateful.
