### ISSUE TITLE
updateHead does not add any new tags

### ISSUE THREAD

**Issue by sutra** [ktquez/vue-head#53]
https://github.com/ktquez/vue-head/blob/93b4d2e6b1dd8eb964befe0dfd806a9fb4edf4f0/vue-head.js#L156-L159

These lines make the updateHead event does not add any new tags. So we cannot add new tags asynchronously.

For example:
```
      meta:  function () {
        var metaData = []
        if (this.asyncData) { // this.asyncData is filled asynchronously.
          metaData.push({ name: 'asyncData', content: this.asyncData })
        } else {
          // the following line cannot be omitted, otherwise the tag will not be appended to DOM.
          metaData.push({ name: 'asyncData', content: '' })
        }

        console.log('metaData: %O', metaData)
        return metaData
      }
```

**Comment by Christilut** [comment]
I have the same problem

```
  data() {
    return {
      googleTitle: ''
    }
  },

  head: {
    meta: [
      { itemprop: 'name', content: this.googleTitle }
    ]
  },

  mounted() {
    this.googleTitle  = this.blogItem.title

    this.$emit('updateHead')
  }
```

DevTools confirm that `this.googleTitle` is correct but in my `<head>` the value is `undefined`

**Comment by sutra** [comment]
@Christilut actually yours problem is not same as mine, you should use function instead, try this:

```
  data() {
    return {
      googleTitle: ''
    }
  },

  head: {
    meta: function () {
      return [
        { itemprop: 'name', content: this.googleTitle }
      ]
    }
  },

  mounted() {
    this.googleTitle  = this.blogItem.title

    this.$emit('updateHead')
  }
```

**Comment by Christilut** [comment]
Thanks

**Comment by eh3anr** [comment]
I have the same problem 
`    link: function(){
      let output = []
      if (this.productsData.all) {
        let page = parseInt(this.productsData.all.current_page) || 1
        if (page === 1) {
          output.push({ rel: 'canonical', href: base_url, id: 'canonical' })
        } else {
          output.push({ rel: 'canonical', href: base_url+this.$route.path, id: 'canonical' })
        }
        if (page !== 1) {
          output.push({ rel: 'prev', href: `${base_url}/page/${page-1}` })
        }
        if (page < this.productsData.all.last_page) {
          output.push({ rel: 'next', href: `${base_url}/page/${page+1}` })
        }
      }
      return output
    }
`
