### ISSUE TITLE
For me, only 'title' is working, metadata's aren't.

### ISSUE THREAD

**Issue by Kuchiriel** [ktquez/vue-head#54]
I am using webpack, vue2.

![image](https://user-images.githubusercontent.com/4648891/31842586-9fcc465e-b5cd-11e7-872a-d6fef247208f.png)

![image](https://user-images.githubusercontent.com/4648891/31842611-bab82eec-b5cd-11e7-9aae-88906ea06d97.png)

Any particular reason for that?

**Comment by ktquez** [comment]
@Kuchiriel 
It adds after loaded on the page, use the browser inspect that the tags will be there.

**Comment by Kuchiriel** [comment]
@ktquez Thanks for the answer!

In this way, [Facebook Debugger](https://developers.facebook.com/tools/debug/sharing/?q=) is capable of extracting the metadata? Because it is not working with me.

**Comment by Kuchiriel** [comment]
@ktquez Oh!, Thanks!

Facebook debugger is capable of extracting the metadate even if its added after?

**Comment by ktquez** [comment]
@Kuchiriel 
The Debugger, I think so.
