### ISSUE TITLE
Question: Why are my og meta tags not working?

### ISSUE THREAD

**Issue by NNTin** [ktquez/vue-head#55]
Website in question: https://nntin.github.io/pasteview/?paste=32z9wKpi  
Source code: https://github.com/NNTin/pasteview

When posting the website to Discord or Twitter the information from the meta tags aren't retrieved. What am I doing wrong?

**Comment by ktquez** [comment]
@NNTin 
So far, only Google and Bing have been able to identify dynamic meta tags in SPA.
To resolve this problem you need to use SSR.
