### ISSUE TITLE
How can i change the information in the meta function

### ISSUE THREAD

**Issue by Shadomax** [ktquez/vue-head#56]
Hello, thanks for sure a library, it's really helping me but i will like to know how to change the content in the meta function Asynchronously
for example
`self.meta: function () {
          return [
             { name: 'description', content: this.meta.description, id: 'desc' },
             { name: 'application-name', content: this.meta.application_name },
            // Twitter
            { name: 'twitter:title', content: this.title },
            // with shorthand
            { n: 'twitter:description', c: this.meta.description },
            // Google+ / Schema.org
            { itemprop: 'name', content: this.meta.application_name },
            { itemprop: 'description', content: this.meta.description },
            // Facebook / Open Graph
            { property: 'fb:app_id', content: '15024009' },
            { property: 'og:title', content: this.title },
            // with shorthand
            { p: 'og:image', c: 'http://example.com/static/favicon.png' }
          ]
        }`

**Comment by ktquez** [comment]
@Shadomax 
If I understand you correctly, you can use `updateHead` to rewrite the tags
https://github.com/ktquez/vue-head#update-elements-with-asynchronous-data-or-after-page-loaded

**Comment by Shadomax** [comment]
@ktquez i have done so but only the title changes:

`getAsyncData: function () {
      var self = this
      window.setTimeout(function () {
        var meta = self.meta
        self.profile = self.artist
        self.title = self.profile.stagename + ' | ' + self.title
        self.meta = function () {
          return [
            { name: 'description', content: self.title, id: 'desc' },
            { name: 'application-name', content: meta.application_name },
            { name: 'twitter:title', content: self.title },
            { n: 'twitter:description', c: self.meta.description },
            { itemprop: 'name', content: self.meta.application_name },
            { itemprop: 'description', content: self.meta.description },
            { property: 'fb:app_id', content: '150240095600075' },
            { property: 'og:title', content: self.title },
            { p: 'og:image', c: self.title }
          ]
        }
        self.$emit('updateHead')
      }, 1000)
    },`

please help me with the right syntax

**Comment by ktquez** [comment]
@Shadomax 

`self.head.title`
`self.head.meta`
