### ISSUE TITLE
Incorrect title in router-views

### ISSUE THREAD

**Issue by ChambreNoire** [ktquez/vue-head#58]
Hi,

I'm having trouble integrating vue-head with my project. The title shows up in my root single file component (although it's rendered 'My title |' unless I manually specify an empty separator) :

```js
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
  export default {
    name: 'app',
    head: {
      title: {
        inner: 'My title',
      },
    }
  }
</script>
```

However using exactly the same format head definition in the various vue-router route components, I get 'undefined |'.

Any ideas?

Cheers

**Comment by ktquez** [comment]
Set a default title in your `index.html`
