### ISSUE TITLE
Replace Existing Meta Information

### ISSUE THREAD

**Issue by keithgulbro** [ktquez/vue-head#63]
Hi there,

Thanks for making a great plugin!

My issue is that my application uses Laravel 5 backend as the API and VueJS to render the frontend, since I don't want to prerender/SSR anything yet I need some way for search engines to index my application so I thought perhaps I could set static meta tags with default application information and then when a user navigates to a specific VueJS route the meta & title information would update however that isn't the case. Instead, it seems this plugin is prepending my desired title content to the static value I set in my index.html file and not updating any of the static meta information I set. 

I.E.

My index.html file head tag contains the following:

```
    <title>MapMate | Create, Share and Explore Maps of Your World</title>
    <!-- Search Engine -->
    <meta name="description" content="Create, Share and Explore interesting maps and places near you or around the world. Find, favorite and follow maps. Upload image's of your adventures quickly.">
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="MapMate">
    <meta itemprop="description" content="Create, Share and Explore interesting maps and places near you or around the world. Find, favorite and follow maps. Upload image's of your adventures quickly.">
    <!-- Twitter -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="MapMate">
    <meta name="twitter:description" content="Create, Share and Explore interesting maps and places near you or around the world. Find, favorite and follow maps. Upload image's of your adventures quickly.">
    <meta name="twitter:image:src" content="https://mapmate.io/images/default.jpg">
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="MapMate">
    <meta name="og:description" content="Create, Share and Explore interesting maps and places near you or around the world. Find, favorite and follow maps. Upload image's of your adventures quickly.">
    <meta name="og:image" content="https://mapmate.io/images/default.jpg">
    <meta name="og:url" content="https://mapmate.io">
    <meta name="og:site_name" content="MapMate">
    <meta name="og:locale" content="en_US">
    <meta name="fb:admins" content="787749717">
    <meta name="fb:app_id" content="1961811424138834">
    <meta name="og:type" content="website">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

**Comment by Raiondesu** [comment]
@ktquez, this is serious stuff. Can you consider this?

**Comment by ktquez** [comment]
@keithgulbro 
Sorry for the delay, I'm sick and I'm not working at the moment.

If anyone can help you, I thank you.

I did not quite understand your question, you want to replace the data when navigating between routes, is that it?

If so, you can check this link in the document.
https://github.com/ktquez/vue-head#replace-content-the-elements

**Comment by keithgulbro** [comment]
@ktquez Thanks for your response ktquez. Yes, I have an index.html file with an HTML title tag and a bunch of meta tags. When I update the head section using your plugin it seems to duplicate the meta tags, instead of overwriting them like I was expecting. Additionally, the title tag becomes updated to concatenate the new title and the static title I have set in my index.html file. I would like my static title tag content to be replaced with the new title content I am setting using your plugin. Any suggestions?

**Comment by ktquez** [comment]
To replace and not to repeat, you need to set an ID for each meta tag you want to replace. As in the example:
`{ name: 'description', content: 'A description of the page', id: 'desc' }`

---

The title you customized?
https://github.com/ktquez/vue-head#default-custom-title

---

I am very willing to refactor and update this plugin, I believe that next month I will make all the updates and improvements possible. This project has not been committed for a long time.

Next month we will have news.

I'm very happy for you to use "vue-head".
