### ISSUE TITLE
Using computed properties

### ISSUE THREAD

**Issue by lochstar** [ktquez/vue-head#68]
Hi,

Are there any plans to enable the use of computed properties? I'm currently setting the title attribute to data and manually emitting `updateHead` when the title has changed. It'd be great if this lib supported computed properties and updated automatically.

Let me know your thoughts.
Cheers

**Comment by ktquez** [comment]
@lochstar 
Yes, a new version is being developed, where you will not have to do the update manually.
It will be available between this week and the next.

**Comment by lochstar** [comment]
Cool, I'll look out for it. Thanks.
