### ISSUE TITLE
vue-router + vue-head + keep-alive don't update title

### ISSUE THREAD

**Issue by terranc** [ktquez/vue-head#7]

**Comment by ktquez** [comment]
@terranc Thanks for feedback, I will correct it to support vue-router hooks.
:)

**Comment by Piterden** [comment]
Got the same trouble. Title not updating when you try to activate earlier resolved component (router-page which you've visited before). When page-component isn't resolved yet changing titles works fine.

**Comment by ktquez** [comment]
@Piterden =)
Thank you for receiving the request, and merged.
I will set a tag version and available with the changes.

**Comment by ktquez** [comment]
Add version tag 1.0.6 and force dependencies to VueRouter in package.json
