### ISSUE TITLE
head\link\stylesheet doesn't work

### ISSUE THREAD

**Issue by Eric-Bryan** [ktquez/vue-head#70]
Hello,

I would like to set dynamically the css file of my vue.

I have reached to set the title using vue-head.
I set a css file into a link tag using vue-head but the css class don't work in my page (the <div class="titleRed"> is not set to red).

Here is my App.vue :

(sorry I haven't reached to insert my code correctly)

template
  div id="app"
    div class="titleRed">Example at 14h35 /div
 /div
/template

`<script>

export default {
  name: 'App',
  components: {
  },
  head: {
    title: {
      inner: 'It will be a pleasure 123'
    },
    link: [         
      {
        rel:'stylesheet',
        href:'./style.css'
      }
      ]
  }
}

</script>`

I checked that the css file (style.css) is in the same folder than App.vue and that the class "titleRed" is set in the style.css file.

In Google dev tools I have the : link rel="stylesheet" href="./style.css"

What have I missed ?

Thanks a lot in advance.

Eric.

**Comment by Eric-Bryan** [comment]
2nd Question : 
Is there a way to set href of link with a data ?
Thanks a lot in advance.

**Comment by ktquez** [comment]
@Eric-Bryan 
**First question**
In this case you can use require ('my-css-path')

**Second question**
If I understand correctly, you can find how to do it here.
https://github.com/ktquez/vue-head#using-this
