### ISSUE TITLE
The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

### ISSUE THREAD

**Issue by sprite26** [ktquez/vue-head#74]
i think the problem is that it render after the css style tags that i have.. but how should i fix that ?

**Comment by ktquez** [comment]
I didn't quite understand your doubt.

**Comment by emiel187** [comment]
I don't think the facebook crawler runs javascript. So Open Graph properties won't work in vue. At least for now. Google already runs the javascript during crawling. For my current project server side rendering seems to be a bit of a headache, but that seems to be the best solution.
