### ISSUE TITLE
using with prerender-spa-plugin is causing title and meta tags to be displayed twice

### ISSUE THREAD

**Issue by praneethmendu** [ktquez/vue-head#76]
Hi, Firstly, thanks for the amazing work you do, hope they decide to make everyone's life better by making vue-head a standard part of vue soon.

I am not sure this is an issue with vue-head but please forgive me if I am wasting your time.

This issue only happens when live on netlify ( without their prerender option active ), not while being served locally.

the live site shows :
`<title>about | anonplayer   about | anonplayer</title>`
but my component has 

```
  head: {  
    title: {
      inner: "about | anonplayer",
      separator: ' ',
    }, ...
```
 and this happens for every page of my single page app

and this is also happening to meta tags i set using vue-head where there are two sets of the tags i intended to have.

looks like [this](https://imgur.com/a/TZhOLKc)

I have the default prerender settings : 
```
      config.plugins.push(new PrerenderSPAPlugin({
        // Required - The path to the webpack-outputted app to prerender.
        staticDir: path.join(__dirname, 'dist'),
        // Required - Routes to render.
        routes: ['/', '/about'].concat(contracts.map(each => `/${each.abi}/${each.contract}`)),
      }))
```

**Comment by BorysTyminski** [comment]
I have following code for title in my index component:

    export default {
        head: {
            title: function () {
                return {
                    inner: this.$options.filters.translate('yacht charter'),
                    separator: ' ',
                    id: 'indexTitle'
                }
            },

I'm also using prerender-spa-plugin. Title at first is once (when I use show code ctrl+U) but when javascript loads and execute, it double title.

This happen only to prerendered app.

I'm doing something wrong?

**Comment by bigsee** [comment]
@BorysTyminski I was searching for ages for the reason my titles were duplicating when using prerender-spa-plugin and yours was the only thing that fixed it! Lifesaver! Thank you :)

Is there an option to set complement and separator rather than hacking around inside the package?

**Comment by bigsee** [comment]
Maybe that's what this option is for: https://github.com/ktquez/vue-head#default-custom-title ?

**Comment by ktquez** [comment]
Do you still get this error?
Set title information in `Vue.use` working? (https://github.com/ktquez/vue-head#default-custom-title)
Do you have any repositories to analyze?

**Comment by ktquez** [comment]
I closed the issue, but if you still have questions, just open again, ok?
