### ISSUE TITLE
Cannot change meta using the mounted data

### ISSUE THREAD

**Issue by waggyman** [ktquez/vue-head#78]
Hi,

I have problem on set the meta dynamically for my dynamic route:

let's say I have route `/job/:jobDetail`

And every different `jobDetail` I want the description meta is changed automatically. Here is the code that I've done so far.

**jobDetail.vue**

```js
head: {
        title: () => ({
            inner: 'Testing title'
        }),
        meta: function () {
            return [
                { name: 'description', content: this.description},
            ]
        }
},
data: () => ({
   description: ''
}),
mounted () {
   const job = axios.get(config.baseUrl + '/' + this.$router.param.jobDetail)
   this.description: 'Something New from ' + job.name
}
```

But the result that I get is empty content from browser like this:

![Screen Shot 2019-04-08 at 17 11 31](https://user-images.githubusercontent.com/20678935/55716528-6667a580-5a21-11e9-9019-169d174fccb3.png)

**Comment by ktquez** [comment]
You can emitir `this.$emit('updateHead')` 
- https://github.com/ktquez/vue-head#update-elements-with-asynchronous-data-or-after-page-loaded

**Comment by waggyman** [comment]
Okay it's working. Actually I didn't know if the emit can also called in mounted or created. Thanks @ktquez

**Comment by ktquez** [comment]
@waggyman 
Nice.
Thank you for using.
