### ISSUE TITLE
Document title switches back on popstate despite route guard (Chrome)

### ISSUE THREAD

**Issue by nicooprat** [ktquez/vue-head#79]
I think this is not really a bug in vue-head, but that would be great to find a way to prevent this here. 

Here's the [reproduction code](https://codesandbox.io/s/7qo8qwqz6) and [example](https://7qo8qwqz6.codesandbox.io) (full window example is needed as we need to see `document.title` changing in the browser tab).

## Steps to reproduce

1. Go to https://7qo8qwqz6.codesandbox.io
2. The page title is home
3. Try to click on "to logged in"
4. Nothing happens, ok
5. Click on the login button (window.isLoggedIn = true), and click again on "to logged in"
6. The page changes, as well as the page title
7. Now click on browser back button

## What's happening

The route doesn't change thanks to the `beforeEach` guard, but the `document.title` changes.

## What should happen

The `document.title` shouldn't change.

## Notes

* I tried a few tricks, like listening for `popstate` event, but I couldn't manage to avoid this behavior.
* The `<title>` tag in the HTML doesn't actually change in this case
* The bug is only on Chrome so I created [an issue there](https://bugs.chromium.org/p/chromium/issues/detail?id=955973&can=2&q=popstate&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20Area%20Feature%20Status%20Owner%20Summary)

**Comment by ktquez** [comment]
I'm sorry for the delay in replying.
I'll check, thanks.

If I find a solution, I reproduce it here.

---

Ahh, I would like to warn you that version 3 will soon be out, it will resolve many bugs, and it may even solve this problem.

**Comment by ktquez** [comment]
Yes, it seems to be something in chrome.
Did you get news about this error?

**Comment by nicooprat** [comment]
Didn't get any news on this. Also, I switched to `vue-meta` a while back and the issue happens too... Agree it looks like something Chrome related.
