### ISSUE TITLE
keep-alive

### ISSUE THREAD

**Issue by exse2** [ktquez/vue-head#88]
I'm sorry, how should keep-alive be supported? In https://github.com/ktquez/vue-head/blob/master/vue-head.js is no mention of "deactivated". If I have a 

			<keep-alive include="find">
				<router-view></router-view>
			</keep-alive>

then the component "find" appears for the first time, head.title.inner of "find" gets set, but if I navigate to some other component, which does not even have .head defined in the component, the head.title.inner of "find" just stays, even though the deactivated() hook of "find" is clearly fired.

**Comment by ktquez** [comment]
Sorry for the delay, you can try `$emit('updateHead')` when the route is modified

**Comment by nathanael540** [comment]
$emit('updateHead')  fires on mounted hook?
