### ISSUE TITLE
vue-head on Vue SPA?

### ISSUE THREAD

**Issue by Sjoerd82** [ktquez/vue-head#89]
Can we confirm that vue-head doesn't (out-of-the-box) work in a Vue SPA for crawler/social purposes? Looking at the page output, I do see the meta tags I specified, however, when I share the page in Facebook or Whatsapp, the OpenGraph tags added are not picked up, probably because Vue dynamically adds them to the DOM too late.

Probably requires pre-rendering (unfortunately)..?

**Comment by ktquez** [comment]
Yes! It's recommended to use prerender or create a project with Nuxt.js for sharing on social networks.

**Comment by Sjoerd82** [comment]
Thanks for confirming that! For those new to front-end dev (like me), these obvious things aren't always immediately obvious ;-).

**Comment by ktquez** [comment]
@Sjoerd82 
Thanks for using!
