### ISSUE TITLE
How about Vue 3?

### ISSUE THREAD

**Issue by akauppi** [ktquez/vue-head#92]
I would need something like this in a Vue 3 beta project.

Do you have plans to cover the upcoming Vue version, as well?

**Comment by egoist** [comment]
I made a version using Vue 3's `<Teleport>` component: https://github.com/egoist/vue-head

**Comment by EmmanuelBeziat** [comment]
@egoist Nice, thanks. Did you consider making it a PR? Would be nice to have.

@ktquez any news on this, please? Vue3 is no longer in beta, and it would be nice to have the ability to switch. Thanks!

**Comment by akauppi** [comment]
I have no further interest / need for this. Learned to live without head injects, in Vue 3. If @EmmanuelBeziat so wishes, I won’t close it tho.

**Comment by ktquez** [comment]
@EmmanuelBeziat @akauppi 
I think the [egoist solution](https://github.com/egoist/vue-head) is lightweight and perfect for Vue 3
