### ISSUE TITLE
REMOVAL OF DEFAULT HEAD COMPLEMENT

### ISSUE THREAD

**Issue by enyoghasim** [ktquez/vue-head#98]
like react helmet is there a way of removing the complement of the default page title on all pages???

your answers will be helpful thanks in advance

**Comment by ktquez** [comment]
Hi @enyoghasim 

You can do this when installing:
```js
Vue.use(VueHead, {
  separator: "",
  complement: ""
});
```

**Comment by ktquez** [comment]
if it's not working, you can see another solution in this issue #94

**Comment by enyoghasim** [comment]
ok thanks man
